const STORAGE_KEY = "karbit-prime-admin-data";
let localGames = [];
let lastEntry = null;
function slugify(text){return String(text).toLowerCase().trim().replace(/[^a-z0-9\s-]/g,"").replace(/\s+/g,"-").replace(/-+/g,"-")}
function renderSummary(){const summary=document.getElementById("localSummary");if(!summary)return;if(!localGames.length){summary.innerHTML=`<div class="mini-row"><span>Belum ada data lokal</span><span>0 item</span></div>`;return}const counts=localGames.reduce((a,i)=>(a[i.category]=(a[i.category]||0)+1,a),{});summary.innerHTML=Object.entries(counts).map(([k,v])=>`<div class="mini-row"><strong>${k.toUpperCase()}</strong><span>${v} item</span></div>`).join("")}
function renderPreview(){const target=document.getElementById("entryPreview");if(!target)return;target.textContent=lastEntry?JSON.stringify(lastEntry,null,2):'{ "status": "Belum ada entry baru" }';renderSummary()}
function saveLocal(){localStorage.setItem(STORAGE_KEY,JSON.stringify(localGames))}
function loadLocal(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");if(Array.isArray(saved))localGames=saved}catch(e){localGames=[]}renderPreview()}
async function loadSiteData(){const res=await fetch("./data/games.json");localGames=await res.json();saveLocal();renderPreview();alert("Data situs berhasil dimuat ke admin lokal.")}
function buildEntry(form){const data=new FormData(form);const title=data.get("title").trim();const category=data.get("category");const genres=String(data.get("genres")||"").split(",").map(s=>s.trim()).filter(Boolean);const platform=[...form.querySelectorAll('input[name="platform"]:checked')].map(i=>i.value);if(!platform.length)throw new Error("Pilih minimal satu platform.");const slug=slugify(title);const sameCategory=localGames.filter(item=>item.category===category);return {id:`${category}-${String(sameCategory.length+1).padStart(3,"0")}`,slug,title,category,genres,platform,version:(data.get("version")||"").trim()||"v1.0",size:(data.get("size")||"").trim()||"-",language:(data.get("language")||"").trim()||"English",status:(data.get("status")||"").trim()||"Updated",emoji:(data.get("emoji")||"").trim()||"🎮",image:(data.get("image")||"").trim(),description:(data.get("description")||"").trim(),detailUrl:(data.get("detailUrl")||"").trim()||`./posts/${category}/${slug}.html`,downloadUrl:(data.get("downloadUrl")||"").trim()||"#",createdAt:new Date().toISOString().slice(0,10)}}
function exportJson(){const blob=new Blob([JSON.stringify(localGames,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="games.json";a.click();URL.revokeObjectURL(url)}
document.addEventListener("DOMContentLoaded",()=>{loadLocal();document.getElementById("loadCurrentData")?.addEventListener("click",async()=>{try{await loadSiteData()}catch(e){alert("Gagal load data situs: "+e.message)}});document.getElementById("exportJson")?.addEventListener("click",exportJson);document.getElementById("clearLocal")?.addEventListener("click",()=>{if(!confirm("Hapus local cache admin?"))return;localGames=[];lastEntry=null;saveLocal();renderPreview()});document.getElementById("copyEntry")?.addEventListener("click",async()=>{if(!lastEntry)return alert("Belum ada entry baru.");await navigator.clipboard.writeText(JSON.stringify(lastEntry,null,2));alert("Entry terakhir berhasil dicopy.")});document.getElementById("importJson")?.addEventListener("change",async e=>{const file=e.target.files?.[0];if(!file)return;const text=await file.text();const data=JSON.parse(text);if(!Array.isArray(data))return alert("File JSON tidak valid.");localGames=data;saveLocal();renderPreview();alert("games.json berhasil diimport.")});document.getElementById("gameForm")?.addEventListener("submit",e=>{e.preventDefault();try{const entry=buildEntry(e.currentTarget);localGames.unshift(entry);lastEntry=entry;saveLocal();renderPreview();e.currentTarget.reset();alert("Game baru masuk ke data lokal. Export games.json untuk menyimpan hasilnya.")}catch(err){alert(err.message)}})})
