const games = [
  {
    id: "renpy-001",
    title: "Moonlight Confession",
    category: "renpy",
    genres: ["Romance", "Drama", "Visual Novel"],
    platform: ["Android", "Windows"],
    version: "v0.21",
    size: "684 MB",
    language: "English",
    status: "Ongoing",
    emoji: "🎭",
    imageClass: "cover-renpy",
    detail: "#",
    download: "#",
    description: "Visual novel romance dengan fokus cerita, pilihan dialog, dan update berkala."
  },
  {
    id: "renpy-002",
    title: "Crimson Summer",
    category: "renpy",
    genres: ["Slice of Life", "Comedy", "Visual Novel"],
    platform: ["Android"],
    version: "v1.0",
    size: "412 MB",
    language: "English",
    status: "Completed",
    emoji: "🌙",
    imageClass: "cover-renpy",
    detail: "#",
    download: "#",
    description: "Story game ringan dengan nuansa santai, karakter kuat, dan cabang pilihan yang jelas."
  },
  {
    id: "renpy-003",
    title: "Night Apartment",
    category: "renpy",
    genres: ["Mystery", "Horror", "Visual Novel"],
    platform: ["Windows"],
    version: "v0.8",
    size: "530 MB",
    language: "English",
    status: "Updated",
    emoji: "🕯️",
    imageClass: "cover-renpy",
    detail: "#",
    download: "#",
    description: "Visual novel misteri untuk Windows dengan cerita gelap, event tersembunyi, dan suasana tegang."
  },

  {
    id: "rpgm-001",
    title: "Dungeon Legacy",
    category: "rpgm",
    genres: ["Fantasy", "Adventure", "RPG"],
    platform: ["Windows"],
    version: "v1.03",
    size: "1.2 GB",
    language: "English",
    status: "Completed",
    emoji: "🗺️",
    imageClass: "cover-rpgm",
    detail: "#",
    download: "#",
    description: "RPG Maker fantasy adventure dengan exploration, dungeon crawl, dan quest-style gameplay."
  },
  {
    id: "rpgm-002",
    title: "Forest Route",
    category: "rpgm",
    genres: ["Adventure", "Exploration", "Fantasy"],
    platform: ["Android", "Windows"],
    version: "v0.95",
    size: "740 MB",
    language: "English",
    status: "Ongoing",
    emoji: "🌲",
    imageClass: "cover-rpgm",
    detail: "#",
    download: "#",
    description: "RPGM dengan fokus petualangan, eksplorasi map, dan progres cerita yang santai."
  },
  {
    id: "rpgm-003",
    title: "Kingdom of Echoes",
    category: "rpgm",
    genres: ["RPG", "Strategy", "Fantasy"],
    platform: ["Windows"],
    version: "v2.0",
    size: "968 MB",
    language: "English",
    status: "Updated",
    emoji: "🏰",
    imageClass: "cover-rpgm",
    detail: "#",
    download: "#",
    description: "RPG Maker dengan elemen strategi, fantasy kingdom, dan progression yang panjang."
  },

  {
    id: "mod-001",
    title: "Prime Patch Pack",
    category: "mod",
    genres: ["Patch", "Gallery Unlock", "QoL"],
    platform: ["Android", "Windows"],
    version: "v2.0",
    size: "78 MB",
    language: "Multi",
    status: "Updated",
    emoji: "🧩",
    imageClass: "cover-mod",
    detail: "#",
    download: "#",
    description: "Patch premium untuk update game, perbaikan bug, QoL, dan gallery unlock dalam satu paket."
  },
  {
    id: "mod-002",
    title: "Night Route Mod",
    category: "mod",
    genres: ["Patch", "Extra Content", "NSFW"],
    platform: ["Windows"],
    version: "v1.4",
    size: "190 MB",
    language: "English",
    status: "Ongoing",
    emoji: "🌆",
    imageClass: "cover-mod",
    detail: "#",
    download: "#",
    description: "Versi custom dengan route tambahan, scene ekstra, dan perubahan balancing."
  },
  {
    id: "mod-003",
    title: "Full Save + Unlock",
    category: "mod",
    genres: ["Save", "Gallery Unlock", "Unlocker"],
    platform: ["Android"],
    version: "v1.1",
    size: "12 MB",
    language: "Multi",
    status: "Completed",
    emoji: "💾",
    imageClass: "cover-mod",
    detail: "#",
    download: "#",
    description: "Paket save lengkap dan unlock gallery untuk pemain yang ingin langsung menikmati semua konten."
  },

  {
    id: "cheat-001",
    title: "Cheat Menu Reloaded",
    category: "cheat",
    genres: ["Cheat", "Menu", "Trainer"],
    platform: ["Android", "Windows"],
    version: "v3.2",
    size: "25 MB",
    language: "English",
    status: "Updated",
    emoji: "⚡",
    imageClass: "cover-cheat",
    detail: "#",
    download: "#",
    description: "Cheat menu siap pakai untuk uang, item, relationship, dan fitur cepat lainnya."
  },
  {
    id: "cheat-002",
    title: "Infinite Money Helper",
    category: "cheat",
    genres: ["Cheat", "Money", "Utility"],
    platform: ["Android"],
    version: "v1.0",
    size: "8 MB",
    language: "English",
    status: "Completed",
    emoji: "💰",
    imageClass: "cover-cheat",
    detail: "#",
    download: "#",
    description: "Tool ringan untuk bantu testing, skip grind, dan atur resource dengan lebih cepat."
  },
  {
    id: "cheat-003",
    title: "Save Editor Prime",
    category: "cheat",
    genres: ["Save Editor", "Cheat", "Utility"],
    platform: ["Windows"],
    version: "v0.9",
    size: "34 MB",
    language: "English",
    status: "Beta",
    emoji: "🛠️",
    imageClass: "cover-cheat",
    detail: "#",
    download: "#",
    description: "Save editor untuk Windows yang cocok buat modder, tester, dan pemain yang ingin kontrol lebih."
  }
];
